# Generated by Django 5.2.8 on 2025-12-02 17:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, help_text='O nome da categoria.', max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(help_text='URL amigável para a categoria.', max_length=120, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, help_text='O nome da etiqueta.', max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(help_text='URL amigável para a etiqueta.', max_length=120, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, help_text='O nome do género.', max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(help_text='URL amigável para o género.', max_length=120, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Lingua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, help_text="O nome da língua (ex: 'Português', 'Inglês').", max_length=100, verbose_name='Nome')),
                ('codigo', models.CharField(db_index=True, help_text="O código da língua (ex: 'pt', 'en').", max_length=10, unique=True, verbose_name='Código ISO 639-1')),
            ],
            options={
                'verbose_name': 'Língua',
                'verbose_name_plural': 'Línguas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, help_text='O nome do país.', max_length=100, verbose_name='Nome')),
                ('iso2', models.CharField(db_index=True, help_text="O código de duas letras do país (ex: 'PT' para Portugal).", max_length=2, unique=True, verbose_name='Código ISO 3166-1 alpha-2')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, help_text="The person's full name.", max_length=250, verbose_name='Name')),
                ('slug', models.SlugField(help_text='URL-friendly identifier.', max_length=260, unique=True, verbose_name='Slug')),
                ('bio', models.TextField(blank=True, help_text='A short biography of the person.', verbose_name='Biography')),
                ('foto', models.URLField(blank=True, help_text="URL for the person's photo.", verbose_name='Photo URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, help_text='O título principal do filme.', max_length=250, verbose_name='Título')),
                ('slug', models.SlugField(help_text='URL amigável gerado a partir do título.', max_length=260, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, help_text='Sinopse ou resumo do enredo do filme.', verbose_name='Descrição')),
                ('ano_lancamento', models.PositiveIntegerField(blank=True, db_index=True, help_text='Ano em que o filme foi lançado.', null=True, verbose_name='Ano de Lançamento')),
                ('popularidade', models.FloatField(db_index=True, default=0, help_text='Métrica de popularidade.', verbose_name='Popularidade')),
                ('media_rating', models.FloatField(db_index=True, default=0, help_text='A média de todas as avaliações dos utilizadores.', verbose_name='Média de Avaliações')),
                ('reviews_count', models.PositiveIntegerField(db_index=True, default=0, help_text='O número total de avaliações recebidas.', verbose_name='Total de Avaliações')),
                ('poster', models.URLField(blank=True, help_text='URL para a imagem do poster do filme.', verbose_name='Poster')),
                ('backdrop', models.URLField(blank=True, help_text='URL para a imagem de fundo (backdrop).', verbose_name='Imagem de Fundo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filmes', to='core.categoria', verbose_name='Categoria')),
                ('etiquetas', models.ManyToManyField(blank=True, related_name='filmes', to='core.etiqueta', verbose_name='Etiquetas')),
                ('generos', models.ManyToManyField(blank=True, related_name='filmes', to='core.genero', verbose_name='Géneros')),
                ('linguas', models.ManyToManyField(blank=True, related_name='filmes', to='core.lingua', verbose_name='Línguas Originais')),
                ('paises', models.ManyToManyField(blank=True, related_name='filmes', to='core.pais', verbose_name='Países de Produção')),
                ('realizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filmes_realizados', to='core.pessoa', verbose_name='Realizador')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
                'ordering': ['-popularidade', '-media_rating', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Elenco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(blank=True, help_text="The role played by the person (e.g., 'Actor', 'Director', 'Screenwriter').", max_length=150, verbose_name='Role')),
                ('ordem_credito', models.PositiveIntegerField(db_index=True, default=0, help_text='The order of appearance in the credits, for sorting (0 is most important).', verbose_name='Credit Order')),
                ('filme', models.ForeignKey(help_text='The movie to which this credit belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='core.filme', verbose_name='Movie')),
                ('pessoa', models.ForeignKey(help_text='The person who is part of the cast or crew.', on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='core.pessoa', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Credit',
                'verbose_name_plural': 'Credits',
                'ordering': ['ordem_credito'],
            },
        ),
        migrations.CreateModel(
            name='Ator',
            fields=[
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pessoa',),
        ),
        migrations.CreateModel(
            name='Realizador',
            fields=[
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pessoa',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='The title of the review.', max_length=200, verbose_name='Title')),
                ('texto', models.TextField(help_text='The full text of the review.', verbose_name='Text')),
                ('rating', models.PositiveSmallIntegerField(help_text='The rating given by the user, from 0 to 10.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('autor', models.ForeignKey(help_text='The user who wrote the review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('filme', models.ForeignKey(help_text='The movie being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.filme', verbose_name='Movie')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="The title of the video (e.g., 'Official Trailer').", max_length=200, verbose_name='Title')),
                ('tipo', models.CharField(choices=[('trailer', 'Trailer'), ('teaser', 'Teaser'), ('behind_the_scenes', 'Behind the Scenes'), ('clip', 'Clip'), ('featurette', 'Featurette')], default='trailer', help_text='The category of the video (e.g., Trailer, Teaser).', max_length=50, verbose_name='Video Type')),
                ('site', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo')], default='youtube', help_text='The platform where the video is hosted (e.g., YouTube, Vimeo).', max_length=50, verbose_name='Platform')),
                ('key', models.CharField(help_text='The unique identifier of the video on the platform (e.g., a YouTube video ID).', max_length=100, verbose_name='Video Key')),
                ('url', models.URLField(blank=True, help_text='The full URL to access the video.', verbose_name='Video URL')),
                ('idioma', models.CharField(blank=True, help_text="The language code of the video (e.g., 'pt-PT', 'en-US').", max_length=10, verbose_name='Language')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('filme', models.ForeignKey(help_text='The movie this video belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.filme', verbose_name='Movie')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_users', to='core.filme', verbose_name='Movie')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Watchlist Item',
                'verbose_name_plural': 'Watchlist Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.filme', verbose_name='Movie')),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
                'ordering': ['-created_at'],
                'unique_together': {('utilizador', 'filme')},
            },
        ),
        migrations.AddIndex(
            model_name='filme',
            index=models.Index(fields=['titulo'], name='core_filme_titulo_bc3c27_idx'),
        ),
        migrations.AddIndex(
            model_name='filme',
            index=models.Index(fields=['popularidade'], name='core_filme_popular_e39f12_idx'),
        ),
        migrations.AddIndex(
            model_name='filme',
            index=models.Index(fields=['media_rating'], name='core_filme_media_r_536c66_idx'),
        ),
        migrations.AddIndex(
            model_name='filme',
            index=models.Index(fields=['ano_lancamento'], name='core_filme_ano_lan_343ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='elenco',
            index=models.Index(fields=['ordem_credito'], name='idx_elenco_ordem'),
        ),
        migrations.AlterUniqueTogether(
            name='elenco',
            unique_together={('filme', 'pessoa', 'papel')},
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('filme', 'autor'), name='unique_review_por_filme_autor'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('filme', 'autor')},
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-created_at'], name='idx_video_created_at'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['tipo'], name='idx_video_tipo'),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(fields=('utilizador', 'filme'), name='unique_watchlist_por_user_filme'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('utilizador', 'filme')},
        ),
    ]
