# Generated by Django 5.2.9 on 2025-12-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filme',
            options={'ordering': ['-media_rating', 'titulo'], 'verbose_name': 'Filme', 'verbose_name_plural': 'Filmes'},
        ),
        migrations.RemoveIndex(
            model_name='filme',
            name='core_filme_titulo_bc3c27_idx',
        ),
        migrations.RemoveIndex(
            model_name='filme',
            name='core_filme_popular_e39f12_idx',
        ),
        migrations.RemoveIndex(
            model_name='filme',
            name='core_filme_media_r_536c66_idx',
        ),
        migrations.RemoveIndex(
            model_name='filme',
            name='core_filme_ano_lan_343ba1_idx',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='etiquetas',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='linguas',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='paises',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='popularidade',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='realizador',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='reviews_count',
        ),
        migrations.AddField(
            model_name='filme',
            name='imdb_id',
            field=models.CharField(blank=True, db_index=True, help_text='O identificador único do filme no IMDb (ex: tt0111161).', max_length=20, null=True, unique=True, verbose_name='ID do IMDb'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='generos',
            field=models.ManyToManyField(blank=True, related_name='filmes', to='core.genero'),
        ),
    ]
