# Generated by Django 5.2.9 on 2025-12-02 21:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_filme_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_por_filme_autor',
        ),
        migrations.AddField(
            model_name='review',
            name='spoiler',
            field=models.BooleanField(default=False, help_text='Marque se a review contém spoilers.', verbose_name='Contém Spoilers'),
        ),
        migrations.AlterField(
            model_name='review',
            name='autor',
            field=models.ForeignKey(help_text='O autor da review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='review',
            name='filme',
            field=models.ForeignKey(help_text='O filme ao qual esta review se refere.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.filme'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='A avaliação do utilizador para o filme, de 1 a 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação'),
        ),
        migrations.AlterField(
            model_name='review',
            name='texto',
            field=models.TextField(help_text='O conteúdo da review.', verbose_name='Texto da Review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='titulo',
            field=models.CharField(blank=True, help_text='Um título opcional para a review.', max_length=200, verbose_name='Título da Review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
    ]
